.486
DATAS SEGMENT USE16
  NUM  DB -19,+28,37,-46,+55,61,-74,+255
  MESG DB 'SUM=',?,';','$'
  MESG2 DB 'MAX=',?,?,'H;','$'
  MESG3 DB 'MIN=',?,?,'H.','$'	    
DATAS ENDS

CODES SEGMENT USE16
    ASSUME CS:CODES,DS:DATAS
START:
    MOV AX,DATAS
    MOV DS,AX
    MOV CX,8;循环8次
    MOV DL,0;存放负数个数
    MOV AL,-128
    MOV DH,0
    MOV BX,OFFSET NUM;将NUM偏移地址赋给BX
AGA:
	CMP BYTE PTR [BX],0;将NUM与0进行比较
	JL NEXT
	JG NEXT2;如果大于0则跳转到NEXT
NEXT:
	INC DL
	CMP [BX],DH
	JG NEXT3
	MOV DH,[BX]
NEXT2:
	CMP [BX],AL;和AL值进行对比
	JL NEXT3;如果小于AL值则跳转到NEXT2
	MOV AL,[BX];如果大于AL值，把BX值赋给AL
NEXT3:
	INC BX;BX->BX+1
	LOOP AGA
	ADD DL,30H;将结果转为ASCII码
        MOV [MESG+4],DL;替换结果为DL值
	SAL AX,8
	MOV BX,OFFSET MESG2+4
	MOV CX,2
AGA2:
	ROL AX,4
	AND AL,0FH
	CMP AL,10
	JC NEXT4
	ADD AL,7
NEXT4:
	ADD AL,30H
	MOV [BX],AL
	INC BX
	LOOP AGA2
	SAL DX,8
	MOV BX,OFFSET MESG3+4
	MOV CX,2
AGA3:
	ROL DX,4
	AND DH,0FH
	CMP DH,10
	JC NEXT5
	ADD DH,7
NEXT5:
	ADD DH,30H
	MOV [BX],DH
	INC BX
	LOOP AGA3
	MOV AH,9;执行9号命令
	MOV DX,OFFSET MESG;将MESG偏移地址赋给DX
	INT 21H
	MOV AH,9
	MOV DX,OFFSET MESG2;将MESG2偏移地址赋给DX
	INT 21H  
	MOV AH,9
	MOV DX,OFFSET MESG3;将MESG3偏移地址赋给DX
	INT 21H  
  MOV AH,4CH
  INT 21H

CODES ENDS
    END START      
